config/routes.rb
Rails.application.routes.draw do
  get '/ping', to: 'ping#index'

  get '/403', to: 'errors#forbidden_403'
  get '/404', to: 'errors#not_found_404'
  get '/500', to: 'errors#internal_server_error_500'
  get '/503', to: 'errors#service_unavailable_503'

  root 'home#index'

  resources :aircraft do
    get 'export', on: :collection
    resources :history, controller: 'aircraft_history'
  end

  scope '/aircraft' do
    resources :views, only: [:create, :show, :destroy], controller: 'datatable_views', as: 'datatable_views'
  end

  resources :analysis, only: [:index]

  scope '/analysis' do
    resources :views, only: [:create, :show, :destroy], controller: 'analysis_views', as: 'analysis_views'
  end

  namespace :reports do
    resources :aircraft_reports, controller: :aircraft_reports, only: [:index]
    resources :forecasts, controller: :forecasts, only: [:index]
  end

  namespace :admin do
    resource :users, controller: :users, only: [:show, :update, :destroy]
  end

  devise_for :user,
    path_names: { sign_in: 'login', sign_out: 'logout' },
    controllers: { registrations: 'registrations', invitations: 'invitations' }

  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:super_admin?) && current_user.super_admin?
  end

  ResqueWeb::Engine.eager_load!
  constraints resque_web_constraint do
    mount ResqueWeb::Engine => '/resque'
  end

end

app/models/analysis_view.rb
class AnalysisView < ActiveRecord::Base
  belongs_to :company

  after_initialize :default_values, unless: :persisted?

  HASHIDS_SALT = "3ubIBZO4N4q2"

  def default_values
    self.name = "Default view" if name.nil?
    self.default_view = true if default_view.nil?
    self.current_view = true if current_view.nil?
    self.pivot_params = {
      "filtersArray": [],
      "rowArray": ["Aircraft Model"],
      "colArray": ["Aircraft Status"],
      "attrArray": [
        "Aircraft Age", "Aircraft Manufacturer", "Aircraft Series", "Aircraft Type", "Build Year", "Engine Model",
        "Engine Variant", "Operator", "Operator Country", "Operator Region", "Seats Configuration"
      ],
      "filters": {},
      "renderer": { "name": "table", "type": "text" },
      "aggregator": { "name": "count", "params": [] }
    }.to_json if pivot_params.nil?
  end
end

app/controllers/analysis/forecasts_controller.rb
module Analysis
  class ForecastsController < ApplicationController
    before_action :authenticate_user!

    def index
      @prezi = ForecastsPresenter.new
    end
  end
end

app/controllers/analysis/reports_controller.rb
module Analysis
  class ReportsController < ApplicationController
    before_action :authenticate_user!

    def index
      @prezi = prezi(query_params)
    end

    private

    def prezi(query_params)
      ReportsPresenter.new(query_params)
    end

    def query_params
      params.permit(:aircraft_type)
    end
  end
end

app/controllers/analysis_controller.rb
class AnalysisController < ApplicationController
  before_action :authenticate_user!

  def index
    @prezi = prezi
  end

  private

  def prezi
    AnalysisPresenter.new(current_user.company)
  end
end

app/views/analysis/index.html.erb
<% content_for :title do %>
  Analysis
<% end %>

<% content_for :nav_left do %>
  <%= render 'nav/analysis' %>
<% end %>

<script type='text/javascript'>
  var data = <%= raw @prezi.aircraft_fleet_json %>;
  var filters_hash = <%= raw @prezi.filters_hash.to_json %>;
  var pivot_params = <%= raw @prezi.current_view.pivot_params.to_json %>;
</script>

<section class='main-content-header'>
  <h1>
    <%= content_for :title %>

    <div class='ctn-header-btns pull-right'>
      <div class='btn-save-img pull-right'>
        <button type='button' id='btn-save-img'>
          <i class='fa fa-file-image-o'></i><span>Save as PNG</span>
        </button>
      </div>

      <div class='btn-save-view dropdown pull-right'>
        <button type='button' data-toggle='dropdown' aria-expanded='true'>
          <i class='fa fa-floppy-o'></i><span>Save view</span>
        </button>
        <ul class='dropdown-menu dropdown-menu-right'>
          <div class='arrow-up'></div>
          <li class='input-group'>
            <input type='text' id='input-save-view' class='form-control' placeholder='Save new view as ...'>
            <span class='input-group-btn'>
              <a class='btn btn-green' id='btn-save-view'>Save</a>
            </span>
          </li>
        </ul>
      </div>

      <div class='btn-saved-views dropdown pull-right'>
        <button type='button' data-toggle='dropdown' aria-expanded='true'>
          <i class='fa fa-file'></i><span>My views</span>
        </button>
        <ul class='dropdown-menu dropdown-menu-right saved-views'>
          <div class='arrow-up'></div>
          <% @prezi.saved_views.each_with_index do |view, index| %>
            <% if index == 0 %>
              <li>
                <a href='<%= analysis_view_path(view.hashid) %>'><%= view['name'] %></a>
                <span class='close' data-analysis-view-hashid='<%= view.hashid %>' data-toggle='modal' data-target='#delete-with-ajax'>
                  <i class='fa fa-times-circle-o'></i>
                </span>
              </li>
            <% else %>
              <li class='divider'></li>
              <li>
                <a href='<%= analysis_view_path(view.hashid) %>'><%= view['name'] %></a>
                <span class='close' data-analysis-view-hashid='<%= view.hashid %>' data-toggle='modal' data-target='#delete-with-ajax'>
                  <i class='fa fa-times-circle-o'></i>
                </span>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>

  </h1>
</section>

<section class='main-content'>
  <div class='ctn-selected-attributes row'>
    <div class='col-sm-4'>
      <div class='filter-attributes strong'>FILTERS</div>
      <ul id='filters'>
        <% @prezi.filtersArray.each do |filter| %>
          <li data-id='<%= filter %>'><%= filter %><i class='fa fa-caret-down pull-right'></i></li>
        <% end %>
      </ul>
    </div>
    <div class='col-sm-4'>
      <div class='row-attributes strong'>ROWS</div>
      <ul id='rows'>
        <% @prezi.rowArray.each do |row| %>
          <li data-id='<%= row %>'><%= row %><i class='fa fa-caret-down pull-right'></i></li>
        <% end %>
      </ul>
    </div>

    <div class='col-sm-4'>
      <div class='column-attribtues strong'>COLUMNS</div>
      <ul id='columns'>
        <% @prezi.colArray.each do |column| %>
          <li data-id='<%= column %>'><%= column %><i class='fa fa-caret-down pull-right'></i></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div id='pivot-container'></div>
</section>

<% @prezi.filters_hash.each do |attribute, values| %>
  <div class='pvtFilterBox' data-attribute='<%= attribute %>' style='display: none;'>
    <h4><%= attribute %> (<%= values.count %>)</h4>
    <div>
      <button class='btn btn-medium-blue btn-select-all pvtFilterBtn' type='button'>Select All</button>
      <button class='btn btn-medium-blue btn-select-none pvtFilterBtn' type='button'>Select None</button>
      <input type='text' class='form-control pvtSearch' placeholder='Filter results'>
    </div>
    <div class='pvtCheckContainer'>
      <% values.each do |value| %>
        <p>
          <label>
            <input type='checkbox' class='pvtFilter' data-attribute='<%= attribute %>' <%= 'checked' if @prezi.checked_filters(attribute, value) %> />
            <span><%= value %></span>
          </label>
        </p>
      <% end %>
    </div>
    <div><button class='btn btn-medium-blue btn-update-filter' type='button'>OK</button></div>
  </div>
<% end %>

<%= render partial: 'utility/delete_with_ajax_modal', locals: {delete_item: 'view'} %>