config/routes.rb
Rails.application.routes.draw do
  get '/ping', to: 'ping#index'

  get '/403', to: 'errors#forbidden_403'
  get '/404', to: 'errors#not_found_404'
  get '/500', to: 'errors#internal_server_error_500'
  get '/503', to: 'errors#service_unavailable_503'

  root 'home#index'

  resources :aircraft do
    get 'export', on: :collection
    resources :history, controller: 'aircraft_history'
  end

  scope '/aircraft' do
    resources :views, only: [:create, :show, :destroy], controller: 'datatable_views', as: 'datatable_views'
  end

  resources :analysis, only: [:index]

  scope '/analysis' do
    resources :views, only: [:create, :show, :destroy], controller: 'analysis_views', as: 'analysis_views'
  end

  namespace :reports do
    resources :aircraft_reports, controller: :aircraft_reports, only: [:index]
    resources :forecasts, controller: :forecasts, only: [:index]
  end

  namespace :admin do
    resource :users, controller: :users, only: [:show, :update, :destroy]
  end

  devise_for :user,
    path_names: { sign_in: 'login', sign_out: 'logout' },
    controllers: { registrations: 'registrations', invitations: 'invitations' }

  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:super_admin?) && current_user.super_admin?
  end

  ResqueWeb::Engine.eager_load!
  constraints resque_web_constraint do
    mount ResqueWeb::Engine => '/resque'
  end

end

app/models/aircraft.rb
class Aircraft < ActiveRecord::Base
  has_many :aircraft_histories, inverse_of: :aircraft

  HASHIDS_SALT = 'dloYZQtiO2yy'

  def self.to_csv(aircraft_fleet, attributes)
    attribute_names = attributes.map do |column|
      Aircraft.human_attribute_name(column)
    end

    CSV.generate(headers: true) do |csv|
      csv << attribute_names
      aircraft_fleet.each do |aircraft|
        csv << aircraft.values_at(*attributes)
      end
    end
  end
end

app/controllers/aircraft_controller.rb
class AircraftController < ApplicationController
  before_action :authenticate_user!

  def index
    @prezi = prezi(query_params: query_params, column_params: column_params)

    respond_to do |format|
      format.html
      format.json {
        render json: {
          column_names: @prezi.column_params_selected,
          sort_column: @prezi.sort_column,
          sort_direction: @prezi.sort_direction,
          aircraft_fleet: @prezi.aircraft_fleet_json
        }
      }
    end
  end

  def show
    @prezi = prezi(id: params[:id])
  end

  def update
    options = Hash.new { |h,k| h[k] = Hash.new(&h.default_proc) }
    options[:user] = current_user.email
    options[:user_comment] = aircraft_params[:user_comment]

    update_params.each do |key, value|
      options[:aircraft][key] = value
    end

    api.update_aircraft(aircraft_params[:msn], aircraft_params[:aircraft_model], options)
    flash[:info] = '<strong>Your suggestion has been submitted.</strong>'
    redirect_to aircraft_path(params[:id])
  end

  def export
    @prezi = prezi(query_params: query_params, column_params: column_params)

    respond_to do |format|
      format.html { redirect_to aircraft_index_path }
      format.csv { send_data Aircraft.to_csv(@prezi.aircraft_fleet_json, @prezi.column_params_selected) }
    end
  end

  private

  def prezi(id: nil, query_params: {}, column_params: {})
    AircraftPresenter.new(id, current_user.company, display_count, sort_column, sort_direction, query_params, column_params)
  end

  def display_count
    params[:display_count] || 25
  end

  def sort_column
    sort_column = params.fetch(:sort_params, {}).permit(:sort_column).fetch(:sort_column, {})
    Aircraft.column_names.include?(sort_column) ? sort_column : "msn"
  end

  def sort_direction
    sort_direction = params.fetch(:sort_params, {}).permit(:sort_direction).fetch(:sort_direction, {})
    %w[asc desc].include?(sort_direction) ? sort_direction : "asc"
  end

  def query_params
    params.fetch(:datatable_filters, {}).permit(
      :msn => [], :aircraft_status => [], :aircraft_manufacturer => [], :aircraft_model => [], :aircraft_type => [],
      :registration => [], :engine_model => [], :engine_variant => [], :operator => [], :operator_country => [],
      :build_year => [], :aircraft_age => [], :seats_configuration => [], :line_number => [], :aircraft_series => [],
      :last_delivery_date => [], :operator_region => []
    )
  end

  def column_params
    params.fetch(:datatable_columns, {}).permit(:selected => [], :available => [])
  end

  def aircraft_params
    params[:aircraft]
  end

  def update_params
    params.fetch(:aircraft, {}).permit(:build_year, :line_number)
  end

  def api
    @api ||= ResolutionsService.instance
  end
end

app/views/aircraft/index.html.erb
<% content_for :title do %>
  Fleet Database
<% end %>

<% content_for :nav_left do %>
  <%= render 'nav/filters' %>
<% end %>

<section class='main-content-header'>
  <h1>
    <button class='btn hide' id='btn-expand-sidebar'><i class='fa fa-filter'></i>Add Filter</button>
    <%= content_for :title %>

    <div class='ctn-header-btns pull-right'>
      <div class='btn-table-settings dropdown pull-right'>
        <button type='button' data-toggle='dropdown' data-submenu='' aria-expanded='true'>
          <i class='fa fa-cog'></i><span>Settings</span>
        </button>
        <ul class='dropdown-menu dropdown-menu-right'>
          <div class='arrow-up'></div>
          <li><a tabindex='0' id='btn-export-csv'><i class='fa fa-long-arrow-down'></i>Download CSV</a></li>
          <li class='divider'></li>
          <li class='dropdown-submenu'>
            <a tabindex='0'><i class='fa fa-bars'></i>Show results</a>
            <ul class='dropdown-menu' id='select-display-count'>
              <li><a tabindex='0'>15</a></li>
              <li class='divider'></li>
              <li><a tabindex='0' selected='selected'>25</a></li>
              <li class='divider'></li>
              <li><a tabindex='0'>50</a></li>
              <li class='divider'></li>
              <li><a tabindex='0'>All</a></li>
            </ul>
          </li>
        </ul>
      </div>

      <div class='btn-display-settings pull-right'>
        <button type='button' data-toggle='modal' data-target='#datatable_settings_container'>
          <i class='fa fa-pencil-square-o'></i><span>Display Settings</span>
        </button>
      </div>

      <div class='btn-save-view dropdown pull-right'>
        <button type='button' data-toggle='dropdown' aria-expanded='true'>
          <i class='fa fa-floppy-o'></i><span>Save view</span>
        </button>
        <ul class='dropdown-menu dropdown-menu-right'>
          <div class='arrow-up'></div>
          <li class='input-group'>
            <input type='text' id='input-save-view' class='form-control' placeholder='Save new view as ...'>
            <span class='input-group-btn'>
              <a class='btn btn-green' id='btn-save-view'>Save</a>
            </span>
          </li>
        </ul>
      </div>

      <div class='btn-saved-views dropdown pull-right'>
        <button type='button' data-toggle='dropdown' aria-expanded='true'>
          <i class='fa fa-file'></i><span>My views</span>
        </button>
        <ul class='dropdown-menu dropdown-menu-right saved-views'>
          <div class='arrow-up'></div>
          <% @prezi.saved_views.each_with_index do |view, index| %>
            <% if index == 0 %>
              <li>
                <a href='<%= datatable_view_path(view.hashid) %>'><%= view['name'] %></a>
                <span class='close' data-datatable-view-hashid='<%= view.hashid %>' data-toggle='modal' data-target='#delete-with-ajax'>
                  <i class='fa fa-times-circle-o'></i>
                </span>
              </li>
            <% else %>
              <li class='divider'></li>
              <li>
                <a href='<%= datatable_view_path(view.hashid) %>'><%= view['name'] %></a>
                <span class='close' data-datatable-view-hashid='<%= view.hashid %>' data-toggle='modal' data-target='#delete-with-ajax'>
                  <i class='fa fa-times-circle-o'></i>
                </span>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>

  </h1>
</section>

<section class='main-content'>
  <div class='filter-container'>
    <% @prezi.datatable_filters_list.each do |filter| %>
      <a class='filter-item' name='<%= filter[:field] %>' value='<%= filter[:value] %>'>
        <span class='close'>&times;</span><%= filter[:field].titleize %>: <span class='strong'><%= filter[:value] %></span>
      </a>
    <% end %>
  </div>

  <div class='results-containter'>
    <div class='table-responsive aircraft-table'>
      <table class='table table-hover'>
        <thead>
          <tr>
            <% @prezi.datatable_columns_selected.each do |column| %>
              <th class='column-name' data-type='<%= column %>' data-sorted='false'>
                <%= Aircraft.human_attribute_name(column) %><i class='fa fa-caret-down'></i>
              </th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @prezi.aircraft_fleet.each do |aircraft| %>
            <tr class='aircraft-row'>
              <% @prezi.datatable_columns_selected.each do |column| %>
                <% if column == 'msn' || column == 'registration' || column == 'line_number'%>
                  <td><a name='<%= column %>' value='<%= aircraft[column] %>' href='<%= aircraft_path(aircraft["hashid"]) %>'><%= aircraft[column] %></a></td>
                <% else %>
                  <td name='<%= column %>' value='<%= aircraft[column] %>'><%= aircraft[column] %></td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

<%= render partial: 'aircraft/partials/aircraft_template' %>
<%= render partial: 'aircraft/partials/datatable_settings' %>
<%= render partial: 'utility/delete_with_ajax_modal', locals: {delete_item: 'view'} %>

app/views/aircraft/show.html.erb
<% content_for :title do %>
  Aircraft
<% end %>

<% content_for :main_wrapper_class do %>
  sidebar-collapsed
<% end %>

<section class='main-content-header'>
  <h1>
    <a class='btn' id='btn-return-to-index' href='<%= aircraft_index_path %>'><span><i class='fa fa-arrow-left'></i>Back</span></a>
    <p><%= content_for :title %></p>
  </h1>
</section>

<section class='main-content'>
  <div class="aircraft-summary-container">
    <table class='table'>
      <thead>
        <tr>
          <th>MSN</th>
          <th>Registration</th>
          <th>Manufacturer</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @prezi.aircraft.msn %></td>
          <td><%= @prezi.aircraft.registration %></td>
          <td><%= @prezi.aircraft.aircraft_manufacturer %></td>
          <td><%= @prezi.aircraft.aircraft_status %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class='aircraft-details-container row'>
    <div class="col-sm-6">
      <div class="container-header">
        <span class="header-title">Aircraft Details</span>
        <button class='btn btn-submit-changes pull-right' data-toggle='modal' data-target='#aircraft-update-container'>Submit Changes</button>
      </div>
      <table class='table'>
        <tbody>
          <tr>
            <td>MSN</td>
            <td><%= @prezi.aircraft.msn %></td>
          </tr>
          <tr>
            <td>Aircraft Status</td>
            <td><%= @prezi.aircraft.aircraft_status %></td>
          </tr>
          <tr>
            <td>Registration</td>
            <td><%= @prezi.aircraft.registration %></td>
          </tr>
          <tr>
            <td>Line Number</td>
            <td><%= @prezi.aircraft.line_number %></td>
          </tr>
          <tr>
            <td>Aircraft Model</td>
            <td><%= @prezi.aircraft.aircraft_model %></td>
          </tr>
          <tr>
            <td>Aircraft Type</td>
            <td><%= @prezi.aircraft.aircraft_type %></td>
          </tr>
          <tr>
            <td>Aircraft Series</td>
            <td><%= @prezi.aircraft.aircraft_series %></td>
          </tr>
          <tr>
            <td>Build Year</td>
            <td><%= @prezi.aircraft.build_year %></td>
          </tr>
          <tr>
            <td>Aircraft Age</td>
            <td><%= @prezi.aircraft.aircraft_age %></td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="col-sm-6">
      <div class="container-header">
        <span class="header-title">Operator Details</span>
      </div>
      <table class='table'>
        <tbody>
          <tr>
            <td>Name</td>
            <td><%= @prezi.aircraft.operator %></td>
          </tr>
          <tr>
            <td>Country</td>
            <td><%= @prezi.aircraft.operator_country %></td>
          </tr>
          <tr>
            <td>Region</td>
            <td><%= @prezi.aircraft.operator_region %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="aircraft-history-container">
    <div class="container-header">
      <span class="header-title">Aircraft History</span>
      <button class='btn btn-submit-changes pull-right' data-toggle='modal' data-target='#new-aircraft-history-container'>Suggest New History</button>
    </div>
    <div class="table-responsive">
      <table class='table'>
        <thead>
          <tr>
            <th>Delivery Date</th>
            <th>Registration</th>
            <th>Operator Name</th>
            <th>Seats Configuration</th>
            <th>Engine Name</th>
            <th>Aircraft Status</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @prezi.aircraft_histories.each do |aircraft_history| %>
          <tr>
            <td><%= ppt_time_utc(aircraft_history.delivery_date) if !aircraft_history.delivery_date.nil? %></td>
            <td><%= aircraft_history.registration %></td>
            <td><%= aircraft_history.operator_name %></td>
            <td><%= aircraft_history.seats_configuration %></td>
            <td><%= aircraft_history.engine_name %></td>
            <td><%= aircraft_history.aircraft_status %></td>
            <td><a class="link-submit-changes" data-aircraft-hashid='<%= @prezi.aircraft.hashid %>' data-aircraft-history-hashid='<%= aircraft_history.hashid %>'>Submit Changes</a></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

<div class="modal" id='aircraft-update-container' tabindex='-1'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class='ctn-modal-header'>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class='ctn-title'></h2>
      </div>
      <%= render partial: 'aircraft/partials/aircraft_update_form' %>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal" id='new-aircraft-history-container' tabindex='-1'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class='ctn-modal-header'>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class='ctn-title'></h2>
      </div>
      <%= render partial: 'aircraft/partials/new_aircraft_history_form' %>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal" id='aircraft-history-update-container' tabindex='-1'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class='ctn-modal-header'>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class='ctn-title'></h2>
      </div>
      <%= render partial: 'aircraft/partials/aircraft_history_update_form' %>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->