config/routes.rb
Rails.application.routes.draw do
  get '/ping', to: 'ping#index'

  get '/403', to: 'errors#forbidden_403'
  get '/404', to: 'errors#not_found_404'
  get '/500', to: 'errors#internal_server_error_500'
  get '/503', to: 'errors#service_unavailable_503'

  root 'home#index'

  resources :aircraft do
    get 'export', on: :collection
    resources :history, controller: 'aircraft_history'
  end

  scope '/aircraft' do
    resources :views, only: [:create, :show, :destroy], controller: 'datatable_views', as: 'datatable_views'
  end

  resources :analysis, only: [:index]

  scope '/analysis' do
    resources :views, only: [:create, :show, :destroy], controller: 'analysis_views', as: 'analysis_views'
  end

  namespace :reports do
    resources :aircraft_reports, controller: :aircraft_reports, only: [:index]
    resources :forecasts, controller: :forecasts, only: [:index]
  end

  namespace :admin do
    resource :users, controller: :users, only: [:show, :update, :destroy]
  end

  devise_for :user,
    path_names: { sign_in: 'login', sign_out: 'logout' },
    controllers: { registrations: 'registrations', invitations: 'invitations' }

  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:super_admin?) && current_user.super_admin?
  end

  ResqueWeb::Engine.eager_load!
  constraints resque_web_constraint do
    mount ResqueWeb::Engine => '/resque'
  end

end

app/models/aircraft.rb
class Aircraft < ActiveRecord::Base
  has_many :aircraft_histories, inverse_of: :aircraft

  HASHIDS_SALT = 'dloYZQtiO2yy'

  def self.to_csv(aircraft_fleet, attributes)
    attribute_names = attributes.map do |column|
      Aircraft.human_attribute_name(column)
    end

    CSV.generate(headers: true) do |csv|
      csv << attribute_names
      aircraft_fleet.each do |aircraft|
        csv << aircraft.values_at(*attributes)
      end
    end
  end
end

app/controllers/aircraft_controller.rb
class AircraftController < ApplicationController
  before_action :authenticate_user!

  def index
    @prezi = prezi(query_params: query_params, column_params: column_params)

    respond_to do |format|
      format.html
      format.json {
        render json: {
          column_names: @prezi.column_params_selected,
          sort_column: @prezi.sort_column,
          sort_direction: @prezi.sort_direction,
          aircraft_fleet: @prezi.aircraft_fleet_json
        }
      }
    end
  end

  def show
    @prezi = prezi(id: params[:id])
  end

  def update
    options = Hash.new { |h,k| h[k] = Hash.new(&h.default_proc) }
    options[:user] = current_user.email
    options[:user_comment] = aircraft_params[:user_comment]

    update_params.each do |key, value|
      options[:aircraft][key] = value
    end

    api.update_aircraft(aircraft_params[:msn], aircraft_params[:aircraft_model], options)
    flash[:info] = '<strong>Your suggestion has been submitted.</strong>'
    redirect_to aircraft_path(params[:id])
  end

  def export
    @prezi = prezi(query_params: query_params, column_params: column_params)

    respond_to do |format|
      format.html { redirect_to aircraft_index_path }
      format.csv { send_data Aircraft.to_csv(@prezi.aircraft_fleet_json, @prezi.column_params_selected) }
    end
  end

  private

  def prezi(id: nil, query_params: {}, column_params: {})
    AircraftPresenter.new(id, current_user.company, display_count, sort_column, sort_direction, query_params, column_params)
  end

  def display_count
    params[:display_count] || 25
  end

  def sort_column
    sort_column = params.fetch(:sort_params, {}).permit(:sort_column).fetch(:sort_column, {})
    Aircraft.column_names.include?(sort_column) ? sort_column : "msn"
  end

  def sort_direction
    sort_direction = params.fetch(:sort_params, {}).permit(:sort_direction).fetch(:sort_direction, {})
    %w[asc desc].include?(sort_direction) ? sort_direction : "asc"
  end

  def query_params
    params.fetch(:datatable_filters, {}).permit(
      :msn => [], :aircraft_status => [], :aircraft_manufacturer => [], :aircraft_model => [], :aircraft_type => [],
      :registration => [], :engine_model => [], :engine_variant => [], :operator => [], :operator_country => [],
      :build_year => [], :aircraft_age => [], :seats_configuration => [], :line_number => [], :aircraft_series => [],
      :last_delivery_date => [], :operator_region => []
    )
  end

  def column_params
    params.fetch(:datatable_columns, {}).permit(:selected => [], :available => [])
  end

  def aircraft_params
    params[:aircraft]
  end

  def update_params
    params.fetch(:aircraft, {}).permit(:build_year, :line_number)
  end

  def api
    @api ||= ResolutionsService.instance
  end
end

app/views/aircraft/partials/_aircraft_history_update_form.erb
<div class="form-horizontal">
  <div class="form-description">
    <h2>Aircraft History Details</h2>
    <p class="sub">Existing merge data</p>
  </div>

  <div class="details-container"></div>

  <div class="comments-container">
    <div class="comment-input">
      <div class="form-group">
        <label class="control-label" for="aircraft_history_user_comment">Please describe what's wrong</label>
        <textarea class="form-control" name="aircraft_history[user_comment]" id="user-comment"></textarea>
      </div>
    </div>
  </div>

  <div class="clearfix buttons-container">
    <input type="submit" name="submit" value="Submit Changes" id="btn-save-changes" class="btn btn-dark-blue pull-right">
    <input type="submit" name="submit" value="Delete History" id="btn-delete-history" class="btn btn-green pull-right">
    <a class="btn btn-grey pull-right" data-dismiss="modal">Cancel</a>
  </div>
</div>

<script id='aircraft-history-details-template' type='text/x-handlebars-template'>
  <form class='form-horizontal'>
    <input value='{{aircraft.msn}}' type="hidden" name="msn">
    <input value='{{aircraft.aircraft_model}}' type="hidden" name="aircraft_model">
    <input value='{{aircraft.id}}' type="hidden" name="aircraft_id">
    <input value='{{aircraft_history.delivery_date}}' type="hidden" name="delivery_date">
    <input value='{{aircraft_history.id}}' type="hidden" name="aircraft_history_id">
    <div class='form-group'>
      <label class='control-label col-sm-4' for='aircraft_delivery_date'>Delivery Date</label>
      <div class='col-sm-8'>
        <input placeholder='{{formatDate aircraft_history.delivery_date}}' class='form-control' type='date' name='delivery_date'>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-4' for='aircraft_registration'>Registration</label>
      <div class='col-sm-8'>
        <input placeholder='{{aircraft_history.registration}}' class='form-control' type='text' name='registration'>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-4' for='aircraft_operator_name'>Operator Name</label>
      <div class='col-sm-8'>
        <input placeholder='{{aircraft_history.operator_name}}' class='form-control' type='text' name='operator_name'>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-4' for='aircraft_seats_configuration'>Seats Configuration</label>
      <div class='col-sm-8'>
        <input placeholder='{{aircraft_history.seats_configuration}}' class='form-control' type='text' name='seats_configuration'>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-4' for='aircraft_engine_model'>Engine Name</label>
      <div class='col-sm-8'>
        <input placeholder='{{aircraft_history.engine_name}}' class='form-control' type='text' name='engine_name'>
      </div>
    </div>
    <div class='form-group'>
      <label class='control-label col-sm-4' for='aircraft_aircraft_status'>Aircraft Status</label>
      <div class='col-sm-8'>
        <input placeholder='{{aircraft_history.aircraft_status}}' class='form-control' type='text' name='aircraft_status'>
      </div>
    </div>
  </form>
</script>

app/views/aircraft/partials/_aircraft_template.html.erb
<script id="new-aircraft-template" type="text/x-handlebars-template">
  <thead>
    <tr>
      {{#each column_names}}
        {{#if_equal ../sort_column this}}
          <th class="column-name" data-type="{{this}}" data-sorted="true" data-sorted-direction="{{../../sort_direction}}">
            {{#if_equal ../../sort_direction "asc"}}
              {{human_attribute_name this}}<i class="fa fa-caret-up"></i>
            {{else}}
              {{human_attribute_name this}}<i class="fa fa-caret-down"></i>
            {{/if_equal}}
          </th>
        {{else}}
          <th class="column-name" data-type="{{this}}" data-sorted="false">
            {{human_attribute_name this}}<i class="fa fa-caret-down"></i>
          </th>
        {{/if_equal}}
      {{/each}}
    </tr>
  </thead>
  <tbody>
    {{#each aircraft_fleet as |aircraft aircraft_id|}}
      <tr class='aircraft-row'>
        {{#each ../column_names as |column_name column_name_Id|}}
          {{#if_one_equal column_name 'msn' 'registration' 'line_number'}}
            <td>
              <a name="{{column_name}}" value="{{get_object_value_with_key aircraft column_name}}" href="/aircraft/{{get_object_value_with_key aircraft 'hashid'}}">
                {{get_object_value_with_key aircraft column_name}}
              </a>
            </td>
          {{else}}
            <td name="{{column_name}}" value="{{get_object_value_with_key aircraft column_name}}">{{get_object_value_with_key aircraft column_name}}</td>
          {{/if_one_equal}}
        {{/each}}
      </tr>
    {{/each}}
  </tbody>
</script>

app/views/aircraft/partials/_aircraft_update_form.erb
<%= bootstrap_form_for :aircraft, url: aircraft_path(@prezi.aircraft.hashid),
  html: { method: :patch }, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8" do |f| %>

  <div class="form-description">
    <h2>Aircraft Details</h2>
    <p class="sub">Existing merge data</p>
  </div>

  <div class="details-container">
    <%= f.hidden_field :msn, value: @prezi.aircraft.msn %>
    <%= f.hidden_field :aircraft_model, value: @prezi.aircraft.aircraft_model %>
    <%= f.text_field :build_year, label: 'Build Year', placeholder: @prezi.aircraft.build_year %>
    <%= f.text_field :line_number, label: 'Line Number', placeholder: @prezi.aircraft.line_number %>
  </div>

  <div class="comments-container">
    <div class="comment-input"><%= f.text_area :user_comment, layout: :inline, label: "Please describe what's wrong" %></div>
  </div>

  <div class='clearfix buttons-container'>
    <%= f.submit "Submit Changes", name: 'submit', class: 'btn btn-dark-blue pull-right' %>
    <a class='btn btn-grey pull-right' data-dismiss="modal">Cancel</a>
  </div>
<% end %>

app/views/aircraft/partials/_datatable_settings.html.erb
<div class="modal" id='datatable_settings_container' tabindex='-1'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class='ctn-modal-header'>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class='ctn-title'>Display Settings</h2>
      </div>

      <div class="ctn-sortable-columns row">
        <div class="col-sm-6">
          <div class="title">Available Columns</div>
          <ul id="available">
            <% @prezi.datatable_columns_available.each do |column| %>
              <li data-id="<%= column %>"><%= Aircraft.human_attribute_name(column) %><i class="fa fa-bars pull-right"></i></li>
            <% end %>
          </ul>
        </div>

        <div class="col-sm-6">
          <div class="title">Selected Columns</div>
          <ul id="selected">
            <% @prezi.datatable_columns_selected.each do |column| %>
              <li data-id="<%= column %>"><%= Aircraft.human_attribute_name(column) %><i class="fa fa-bars pull-right"></i></li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class='clearfix buttons-container'>
        <div class="pull-right">
          <a class='btn btn-medium-blue' data-dismiss="modal"><span>Cancel</span></a>
          <a id='btn-save-changes' datatable-view-hashid='<%= @prezi.current_view.hashid %>' class='btn btn-green' data-dismiss="modal"><span>Ok</span></a>
        </div>
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/aircraft/partials/_new_aircraft_history_form.html.erb
<%= bootstrap_form_for :aircraft_history, url: aircraft_history_index_path(@prezi.aircraft.hashid),
  layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8" do |f| %>

  <div class="form-description">
    <h2>New Aircraft History</h2>
  </div>

  <div class="details-container">
    <%= f.hidden_field :msn, value: @prezi.aircraft.msn %>
    <%= f.hidden_field :aircraft_model, value: @prezi.aircraft.aircraft_model %>
    <%= f.date_field :delivery_date, label: 'Delivery Date' %>
    <%= f.text_field :registration, label: 'Registration' %>
    <%= f.text_field :operator_name, label: 'Operator Name' %>
    <%= f.text_field :seats_configuration, label: 'Seats Configuration' %>
    <%= f.text_field :engine_name, label: 'Engine Name' %>
    <%= f.text_field :aircraft_status, label: 'Aircraft Status' %>
  </div>

  <div class="comments-container">
    <div class="comment-input"><%= f.text_area :user_comment, layout: :inline, label: "Comments" %></div>
  </div>

  <div class='clearfix buttons-container'>
    <%= f.submit "Create Aircraft History", name: 'submit', class: 'btn btn-dark-blue pull-right' %>
    <a class='btn btn-grey pull-right' data-dismiss="modal">Cancel</a>
  </div>
<% end %>