config/routes.rb
Rails.application.routes.draw do
  get '/ping', to: 'ping#index'

  get '/403', to: 'errors#forbidden_403'
  get '/404', to: 'errors#not_found_404'
  get '/500', to: 'errors#internal_server_error_500'
  get '/503', to: 'errors#service_unavailable_503'

  root 'home#index'

  resources :aircraft do
    get 'export', on: :collection
    resources :history, controller: 'aircraft_history'
  end

  scope '/aircraft' do
    resources :views, only: [:create, :show, :destroy], controller: 'datatable_views', as: 'datatable_views'
  end

  resources :analysis, only: [:index]

  scope '/analysis' do
    resources :views, only: [:create, :show, :destroy], controller: 'analysis_views', as: 'analysis_views'
  end

  namespace :reports do
    resources :aircraft_reports, controller: :aircraft_reports, only: [:index]
    resources :forecasts, controller: :forecasts, only: [:index]
  end

  namespace :admin do
    resource :users, controller: :users, only: [:show, :update, :destroy]
  end

  devise_for :user,
    path_names: { sign_in: 'login', sign_out: 'logout' },
    controllers: { registrations: 'registrations', invitations: 'invitations' }

  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:super_admin?) && current_user.super_admin?
  end

  ResqueWeb::Engine.eager_load!
  constraints resque_web_constraint do
    mount ResqueWeb::Engine => '/resque'
  end

end

app/views/nav/_analysis.html.erb
<aside class='sidebar analysis-sidebar'>
  <div class='renderers-container'>
    <div class='title'>TABLE VIEW</div>
    <select class='selectpicker renderers' name='renderers'>
      <option name='renderer' data-renderer-type='text' value='table' <%= 'selected' if @prezi.selected('renderer', 'name', 'table') %>>Table</option>
      <option name='renderer' data-renderer-type='text' value='tableBarChart' <%= 'selected' if @prezi.selected('renderer', 'name', 'tableBarChart') %>>Table Barchart</option>
      <option name='renderer' data-renderer-type='text' value='heatmap' <%= 'selected' if @prezi.selected('renderer', 'name', 'heatmap') %>>Heatmap</option>
      <option name='renderer' data-renderer-type='text' value='colHeatmap' <%= 'selected' if @prezi.selected('renderer', 'name', 'colHeatmap') %>>Col Heatmap</option>
      <option name='renderer' data-renderer-type='text' value='rowHeatMap' <%= 'selected' if @prezi.selected('renderer', 'name', 'rowHeatMap') %>>Row Heatmap</option>
      <option name='renderer' data-renderer-type='svg' value='areaChart' <%= 'selected' if @prezi.selected('renderer', 'name', 'areaChart') %>>Area Chart</option>
      <option name='renderer' data-renderer-type='svg' value='barChart' <%= 'selected' if @prezi.selected('renderer', 'name', 'barChart') %>>Bar Chart</option>
      <option name='renderer' data-renderer-type='svg' value='lineChart' <%= 'selected' if @prezi.selected('renderer', 'name', 'lineChart') %>>Line Chart</option>
      <option name='renderer' data-renderer-type='svg' value='scatterChart' <%= 'selected' if @prezi.selected('renderer', 'name', 'scatterChart') %>>Scatter Chart</option>
      <option name='renderer' data-renderer-type='svg' value='stackedBarChart' <%= 'selected' if @prezi.selected('renderer', 'name', 'stackedBarChart') %>>Stacked Bar Chart</option>
      <option name='renderer' data-renderer-type='text' value='tsvExport' <%= 'selected' if @prezi.selected('renderer', 'name', 'tsvExport') %>>TSV Export</option>
    </select>
  </div>

  <div class='aggregators-container'>
    <div class='title'>VALUES</div>
    <select class='selectpicker aggregators' name='aggegators'>
      <option name='aggregator' value='count' <%= 'selected' if @prezi.selected('aggregator', 'name', 'count') %>>Count</option>
      <option name='aggregator' value='countUnique' <%= 'selected' if @prezi.selected('aggregator', 'name', 'countUnique') %>>Count Unique Values</option>
      <option name='aggregator' value='listUnique' <%= 'selected' if @prezi.selected('aggregator', 'name', 'listUnique') %>>List Unique Values</option>
      <option name='aggregator' value='sum' <%= 'selected' if @prezi.selected('aggregator', 'name', 'sum') %>>Sum</option>
      <option name='aggregator' value='intergerSum' <%= 'selected' if @prezi.selected('aggregator', 'name', 'intergerSum') %>>Integer Sum</option>
      <option name='aggregator' value='average' <%= 'selected' if @prezi.selected('aggregator', 'name', 'average') %>>Average</option>
      <option name='aggregator' value='min' <%= 'selected' if @prezi.selected('aggregator', 'name', 'min') %>>Minimum</option>
      <option name='aggregator' value='max' <%= 'selected' if @prezi.selected('aggregator', 'name', 'max') %>>Maximum</option>
    </select>
    <select class='selectpicker attributes' data-live-search='true' title='Select' data-dropup-auto='false' <%= 'disabled' if @prezi.selected('aggregator', 'name', 'count').present? %>>
      <% @prezi.attribute_names.each do |attribute| %>
        <option name='attribute' value='<%= attribute %>' <%= 'selected' if @prezi.selected('aggregator', 'params', attribute) %>><%= attribute %></option>
      <% end %>
    </select>
  </div>

  <div class='attributes-container'>
    <div class='title'>AVAILABLE ATTRIBUTES</div>
    <div class='ctn-available-attributes'>
      <ul id='available'>
        <% @prezi.attrArray.each do |attribute| %>
          <li data-id='<%= attribute %>'><%= attribute %><i class='fa fa-caret-down pull-right'></i></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class='sidebar-shadow'></div>
</aside>

app/views/nav/_filters.html.erb
<aside class='sidebar filters-sidebar'>
  <div class='btn-collapse-sidebar'>Filters<i class='fa fa-close'></i></div>

  <ul class='nav nav-pills nav-stacked'>
    <li data-toggle='collapse' href='#aircraft_status'>
      <a class='filter-category'><i class='fa fa-chevron-right'></i>AIRCRAFT STATUS</a>
    </li>
    <ul class='nav nav-pills nav-stacked collapse' id='aircraft_status'>
      <%= bootstrap_form_for :filters, html: {class: 'filter-content'} do |f| %>
        <div class='filter' data-field='status'>
          <% @prezi.filters('aircraft_status').each do |status| %>
            <%= f.check_box status, {name: 'aircraft_status', label: status, checked: @prezi.checked('aircraft_status', status)}, status %>
          <% end %>
        </div>
      <% end %>
    </ul>

    <li data-toggle='collapse' href='#aircraft'>
      <a class='filter-category'><i class='fa fa-chevron-right'></i>AIRCRAFT</a>
    </li>
    <ul class='nav nav-pills nav-stacked collapse' id='aircraft'>
      <%= bootstrap_form_for :filters, html: {class: 'filter-content'} do |f| %>
        <div class='filter-name'>Aircraft Manufacturer</div>
        <select class='selectpicker' name='aircraft_manufacturer' data-live-search='true' data-icon-base='fa' data-tick-icon='fa-check' multiple title='Select' data-dropup-auto='false'>
          <% @prezi.filters('aircraft_manufacturer').each do |filter| %>
            <option name='aircraft_manufacturer' value='<%= filter %>' <%= 'selected' if @prezi.selected('aircraft_manufacturer', filter) %>><%= filter.titleize %></option>
          <% end %>
        </select>

        <div class='filter-name'>Aircraft Model</div>
        <select class='selectpicker' name='aircraft_model' data-live-search='true' data-icon-base='fa' data-tick-icon='fa-check' multiple title='Select' data-dropup-auto='false'>
          <% @prezi.filters('aircraft_model').each do |filter| %>
            <option name='aircraft_model' value='<%= filter %>' <%= 'selected' if @prezi.selected('aircraft_model', filter) %>><%= filter.titleize %></option>
          <% end %>
        </select>

        <div class='filter-name'>Aircraft Type</div>
        <select class='selectpicker' name='aircraft_type' data-live-search='true' data-icon-base='fa' data-tick-icon='fa-check' multiple title='Select' data-dropup-auto='false'>
          <% @prezi.filters('aircraft_type').each do |filter| %>
            <option name='aircraft_type' value='<%= filter %>' <%= 'selected' if @prezi.selected('aircraft_type', filter) %>><%= filter.titleize %></option>
          <% end %>
        </select>

        <div class='filter-name'>Aircraft Series</div>
        <select class='selectpicker' name='aircraft_series' data-live-search='true' data-icon-base='fa' data-tick-icon='fa-check' multiple title='Select' data-dropup-auto='false'>
          <% @prezi.filters('aircraft_series').each do |filter| %>
            <option name='aircraft_series' value='<%= filter %>' <%= 'selected' if @prezi.selected('aircraft_series', filter) %>><%= filter.titleize %></option>
          <% end %>
        </select>

        <div class='filter-name'>Engine Model</div>
        <select class='selectpicker' name='engine_model' data-live-search='true' data-icon-base='fa' data-tick-icon='fa-check' multiple title='Select' data-dropup-auto='false'>
          <% @prezi.filters('engine_model').each do |filter| %>
            <option name='engine_model' value='<%= filter %>' <%= 'selected' if @prezi.selected('engine_model', filter) %>><%= filter.titleize %></option>
          <% end %>
        </select>

        <div class='filter-name'>Build Year</div>
        <select class='selectpicker' name='build_year' data-live-search='true' data-icon-base='fa' data-tick-icon='fa-check' multiple title='Select' data-dropup-auto='false'>
          <% @prezi.filters('build_year').each do |filter| %>
            <option name='build_year' value='<%= filter %>' <%= 'selected' if @prezi.selected('build_year', filter) %>><%= filter %></option>
          <% end %>
        </select>

        <div class='filter-name'>Seats Configuration</div>
        <select class='selectpicker' name='seats_configuration' data-live-search='true' data-icon-base='fa' data-tick-icon='fa-check' multiple title='Select' data-dropup-auto='false'>
          <% @prezi.filters('seats_configuration').each do |filter| %>
            <option name='seats_configuration' value='<%= filter %>' <%= 'selected' if @prezi.selected('seats_configuration', filter) %>><%= filter.titleize %></option>
          <% end %>
        </select>
      <% end %>
    </ul>

    <li data-toggle='collapse' href='#companies'>
      <a class='filter-category'><i class='fa fa-chevron-right'></i>COMPANIES</a>
    </li>
    <ul class='nav nav-pills nav-stacked collapse' id='companies'>
      <%= bootstrap_form_for :filters, html: {class: 'filter-content'} do |f| %>
        <div class='filter-name'>Operator</div>
        <select class='selectpicker' name='operator' data-live-search='true' data-icon-base='fa' data-tick-icon='fa-check' multiple title='Select' data-dropup-auto='false'>
          <% @prezi.filters('operator').each do |filter| %>
            <option name='operator' value='<%= filter %>' <%= 'selected' if @prezi.selected('operator', filter) %>><%= filter.titleize %></option>
          <% end %>
        </select>
      <% end %>
    </ul>

    <li data-toggle='collapse' href='#misc'>
      <a class='filter-category'><i class='fa fa-chevron-right'></i>MISC</a>
    </li>
    <ul class='nav nav-pills nav-stacked collapse' id='misc'>
      <%= bootstrap_form_for :filters, html: {class: 'filter-content'} do |f| %>
        <div class='filter-name'>Operator Country</div>
        <select class='selectpicker' name='operator_country' data-live-search='true' data-icon-base='fa' data-tick-icon='fa-check' multiple title='Select' data-dropup-auto='false'>
          <% @prezi.filters('operator_country').each do |filter| %>
            <option name='operator_country' value='<%= filter %>' <%= 'selected' if @prezi.selected('operator_country', filter) %>><%= filter.titleize %></option>
          <% end %>
        </select>

        <div class='filter-name'>Operator Region</div>
        <select class='selectpicker' name='operator_region' data-live-search='true' data-icon-base='fa' data-tick-icon='fa-check' multiple title='Select' data-dropup-auto='false'>
          <% @prezi.filters('operator_region').each do |filter| %>
            <option name='operator_region' value='<%= filter %>' <%= 'selected' if @prezi.selected('operator_region', filter) %>><%= filter.titleize %></option>
          <% end %>
        </select>
      <% end %>
    </ul>
  </ul>
  <div class='sidebar-shadow'></div>
</aside>

app/views/nav/_footer.html.erb
<div class='footer'>
  <p class='sub'><i class='fa fa-ft fa-copyright'></i><%= Time.now.year %> Sonar Technologies, Inc.</p>
</div>

app/views/nav/_footer_errors.html.erb
<div class="footer-errors">
  <span class="light-waves"></span>
  <span class="dark-waves"></span>
  <span class="sun"></span>
  <span class="boat"></span>
  <span class="beeps"></span>
  <span class="rocks"></span>

  <%= render partial: 'nav/footer' %>
</div>

app/views/nav/_header.html.erb
<header class="header"> <!--logo start-->
  <div class="navbar-header">
    <a class="nav-left navbar-toggle collapsed" data-toggle="collapse" data-target="#toggle-navbar" aria-expanded="false">
      <i class="fa fa-bars"></i>
    </a>
    <a href="/" class="brand logo"><img src='<%=asset_path 'SonarLogo_White-02.svg' %>'></a>
  </div>

  <div class="collapse navbar-collapse" id="toggle-navbar">
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <%= navbar_item "<i class='fa fa-ft fa-database'></i>Fleet Database", '/aircraft' %>
        <%= navbar_item "<i class='fa fa-ftl fa-bar-chart'></i>Analysis", '/analysis' %>
        <!-- <%= navbar_dropdown "<i class='fa fa-file'></i>Reports" do %>
          <%= bsh_navbar_item "Aircraft Reports", reports_aircraft_reports_path, active: false %>
          <%= bsh_navbar_item 'Forecasting', reports_forecasts_path, active: false %>
        <% end %> -->
      <% end %>
    </ul>

    <ul class="nav navbar-nav nav-right">
      <% if user_signed_in? %>
        <%= navbar_dropdown "<i class='fa fa-user'></i>" do %>
          <%= bsh_navbar_item "Profile", edit_user_registration_path, active: false %>
          <%= bsh_navbar_item 'Users', admin_users_path, active: false %>
          <%= bsh_navbar_item "Logout", destroy_user_session_path, active: false %>
        <% end %>
      <% else %>
        <li>
          <a href='<%=new_user_session_path%>'>Login</a>
        </li>
      <% end %>
    </ul>
  </div>

 </header>

app/views/nav/_header_no_login.html.erb
<header class="header"> <!--logo start-->
  <div class="brand">
    <a href="<%= Rails.configuration.properties['external_url'] %>" class="logo"><img src='<%=asset_path 'SonarLogo_White-02.svg' %>'></a>
  </div>
</header>

app/views/nav/_nav.html.erb
<%= navbar do %>
  <%= navbar_header do %>
    <a class='navbar-brand' href='/'>
      <img src='<%=image_path 'purple_cow_by_vonBorowsky.jpg'%>' alt='Purple Cow' height='40px'> Purple Cow
    </a>
  <% end %>

  <%= navbar_collapse do %>
    <%= navbar_group class: 'foo', id: 'menu' do %>
      <%= navbar_item "Home", '/' %>
      <% if current_user and current_user.isResearcher? %>
        <%= navbar_item "Scenarios", '/scenarios' %>
      <% elsif current_user and current_user.isUser? %>
        <%= navbar_item "User Scenarios", '/user_scenarios' %>
      <% end %>
    <% end %>
    <%= navbar_group align: 'right' do %>
      <% if current_user %>
        <%= navbar_item current_user.display, '/account' %>
        <%= navbar_item 'Logout', logout_path %>
      <% else %>
        <%= navbar_item 'Login', login_path %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/nav/_profile.html.erb
<nav class='nav-page'>
  <div class='nav-header'>Settings</div>
  <ul class="nav nav-pills nav-stacked">
    <%= bsh_navbar_item 'Profile settings', edit_user_registration_path %>
  </ul>

  <div class='nav-header'>Users</div>
  <ul class="nav nav-pills nav-stacked">
    <%= bsh_navbar_item 'Invite users', admin_users_path %>
  </ul>
</nav>